# Generated by Django 3.1.7 on 2021-03-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto_posição',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
