# Generated by Django 3.1.7 on 2021-04-01 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0002_produto_posição_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto_posição',
            new_name='Produto_posicao',
        ),
    ]
